export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <h1>Page Not Found 500</h1>
      </body>
    </html>
  )
}
